
import './globals.css'
import Button from '@mui/material/Button';
import { CiTwitter } from "react-icons/ci";
import { FaInstagram } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";
import Icon_blue from './assets/img/icon.png'
import Image from 'next/image';
import Btn1 from './assets/img/btn1.svg'
import Btn2 from './assets/img/btn2.svg'
import Btn3 from './assets/img/btn3.svg'
import Btn4 from './assets/img/btn4.svg'
import Btn5 from './assets/img/btn5.svg'
import Btn6 from './assets/img/btn6.svg'
import Btn7 from './assets/img/btn7.svg'


export const metadata = {
  title: 'بلو | صفحه اصلی',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="fa" className='bg-white' dir='rtl'>
      <body className=' bg-white'>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
function Footer() {
  return (
    <footer className=' w-full py-5 bg-[#4b94ea] flex justify-center flex-wrap px-28'>
      <section className=' w-full 2xl:container  flex flex-wrap'>
        <section className='w-full lg:w-[75%] order-last lg:order-first '>
            <section className=' w-full'>
              <div className='w-full'>
                <h6 className=' text-2xl font-bold my-3'>امنیت حساب‌ها در بلو</h6>
                <nav className=' *:lg:pe-10 *:pe-0'>
                  <ul>
                    <li>
                      <h6 className='font-bold my-5'>نحوه حفاظت از سرمایه مشتریان</h6>
                      <p className='text-sm'>مبالغ سپرده‌‌های مشتریان در چارچوب ضوابط قانونی و تا سقف قانونی تعیین شده مورد تضمین «صندوق ضمانت سپرده‌های بانک مرکزی» است..</p>
                    </li>
                    <li>
                      <h6 className='font-bold my-5'>پروتکل‌های امنیتی</h6>
                      <p className='text-sm'>در بلو همه پروتکل‌های امنیتی در سیستم‌های زیرساخت بانکی و همچنین استانداردهای بانک مرکزی در خصوص تسویه وجوه و حسابداری، به‌دقت رعایت شده است.</p>
                    </li>
                    <li>
                      <h6 className='font-bold my-5'>آسایش بیشتر</h6>
                      <p className='text-sm'>جایگزینی کارت بانکی با پول کاغذی به دلیل اشراف لحظه‌ای بر دارایی‌های مشتریان، سبب امنیت دوچندان حساب‌های بانکی شده است. این تجربه موفق نشان داده است، روند دیجیتالی شدن منجر به آسایش و راحتی بیشتری برای مشتریان می‌شود.</p>
                    </li>
                  </ul>
                </nav>
              </div>
              <div className='w-full mt-20 leading-8'>
                  <h6 className='text-xl font-bold my-2'>ارتباط با ما</h6>
                  <p>آدرس : تهران، خیابان نلسون ماندلا، خیابان شهید رحیمی، پلاک43</p>
                  <p>تلفن : ۸۷۶۴۱ - ۰۲۱</p>
              </div>
            </section>
        </section>


        {/* ********************************************* */}
        <section className='w-full lg:w-[25%] '>
          <div className=' w-full flex flex-wrap *:w-full  justify-center *:flex *:flex-wrap *:justify-center *:my-2 *:*:w-[160px]'>
            <div>
              <Image src={Btn1}></Image>
            </div>
            <div>
              <Image src={Btn2}></Image>
            </div>
            <div>
              <Image src={Btn3}></Image>
            </div>
            <div>
              <Image src={Btn4}></Image>
            </div>
            <div>
              <Image src={Btn5}></Image>
            </div>
            <div>
              <Image src={Btn6}></Image>
            </div>

            <div>
              <Image src={Btn7}></Image>
            </div>


          </div>
          <div className=' flex justify-center *:mx-1 *:border *:rounded-full *:p-2 mt-5 *:*:text-2xl '>
            <span><CiTwitter></CiTwitter></span>
            <span><FaInstagram></FaInstagram></span>
            <span><FaLinkedin></FaLinkedin></span>

          </div>
          <div className=' flex w-full  justify-center mt-20 pe-10'>
            <p className='text-end text-sm me-3'> Copyright © 2023 bluBank Saman. All rights reserved.</p>
            <Image className=' w-[46px]' src={Icon_blue}></Image>
          </div>
        </section>
      </section>
    </footer>
  )
}